### ISSUE TITLE
CakePHP 5 support

### ISSUE THREAD

**Issue by dereuromark** [bcrowe/cakephp-api-pagination#14]
Is there any plan to add Cake5 support?
Or would a PR to provide this be welcome?

**Comment by bcrowe** [comment]
PR to provide support would more than welcome, Mr. Deuromark. Let me know if you wanna -- otherwise -- I can pick this up sooner than later.

**Comment by dereuromark** [comment]
I sure have a lot on my plate :)
If there was already a branch to test that could sure work out. And we can still do adjustments together where needed prior to a release.
