### ISSUE TITLE
API not getting response Data object

### ISSUE THREAD

**Issue by abhi-meena** [bcrowe/cakephp-api-pagination#9]
Hi there,
I am using this plugin for CakePHP 4 but I am not getting the data, its only giving pagination object.
my function is as follows:-
class ArticlesController extends AppController
{
    /**
     * Index method
     *
     */
    public function index()
    {
        $this->set('articles', $this->paginate($this->Articles));
        $this->set('_serialize', ['articles']);
   }
}

and its giving the output:-
{
    "pagination": {
        "count": 2,
        "current": 2,
        "perPage": 20,
        "page": 1,
        "requestedPage": 1,
        "pageCount": 1,
        "start": 1,
        "end": 2,
        "prevPage": false,
        "nextPage": false,
        "sort": null,
        "direction": null,
        "sortDefault": false,
        "directionDefault": false,
        "completeSort": [],
        "limit": null,
        "scope": null,
        "finder": "all"
    }
}
if I remove $this->paginate() method and use $this->set('articles', $this->Articles->find("all")->toArray()); then output comes:-
{
    "articles": [
        {
            "id": 1,
            "user_id": 1,
            "title": "First Post",
            "slug": "first-post",
            "body": "This is the first post.",
            "published": true,
            "created": "2021-04-29T15:51:26+05:30",
            "modified": "2021-04-29T15:51:26+05:30"
        },
        {
            "id": 2,
            "user_id": 2,
            "title": "Test Category",
            "slug": "testing",
            "body": "Hello Body",
            "published": false,
            "created": "2021-04-29T11:13:06+05:30",
            "modified": "2021-04-29T11:23:28+05:30"
        }
    ]
}
I have tried everything but articles data not coming only pagination is coming.

**Comment by pabloelcolombiano** [comment]
@abhi-meena The setting of serialized data in CakePHP4 slightly changed from CakePHP3:
See [here](https://book.cakephp.org/4/en/views/json-and-xml-views.html#using-data-views-with-the-serialize-key).

Does this solve your issue?

**Comment by abhi-meena** [comment]
> @abhi-meena The setting of serialized data in CakePHP4 slightly changed from CakePHP3:
> See [here](https://book.cakephp.org/4/en/views/json-and-xml-views.html#using-data-views-with-the-serialize-key).
> 
> Does this solve your issue?

@pabloelcolombiano Thanks for your help but it's not working, I have tried all these things but all these things are not working if   I am using cakephp-api-pagination.
If i remove $this->loadComponent('BryanCrowe/ApiPagination.ApiPagination'); this line from AppController.php then data comes but pagination get removed.

**Comment by pabloelcolombiano** [comment]
I suggest you copy paste your controller in a readable incremented manner, using the ApiPagination and the modification I suggested, in order to help me reproduce the issue.

**Comment by abhi-meena** [comment]
here are my files with composer.json
[Controller.zip](https://github.com/bcrowe/cakephp-api-pagination/files/6400526/Controller.zip)

**Comment by pabloelcolombiano** [comment]
I will not open a zip file @abhi-meena, this is not secure.
Did you load the plugin in `Application.php`, as mentioned [here](https://github.com/bcrowe/cakephp-api-pagination#install) and documented on how to in CakePHP4 [there](https://book.cakephp.org/4/en/plugins.html#loading-a-plugin)?

**Comment by abhi-meena** [comment]
> I will not open a zip file @abhi-meena, this is not secure.
> Did you load the plugin in `Application.php`, as mentioned [here](https://github.com/bcrowe/cakephp-api-pagination#install) and documented on how to in CakePHP4 [there](https://book.cakephp.org/4/en/plugins.html#loading-a-plugin)?

Hey @pabloelcolombiano  Thanks for your Help, I got the solution.
public function index()
    {
       $articles = $this->paginate($this->Articles);
       $this->set('articles' ,$articles );
       $this->viewBuilder()->setOption('serialize',['articles']);
}

**Comment by bcrowe** [comment]
Thanks for helping out on this @pabloelcolombiano!
